---
title: "R Notebook"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---


```{r}
psi_df <- read_excel("PSI.xlsx", sheet = "Sheet1")
head(psi_df)
```

```{r}
install.packages('tidyr')
library(tidyr)
```

```{r}
psi_df_tidy <- pivot_longer(psi_df, cols = c('N', 'S', 'E', 'W', 'C'), names_to = 'Region', 
                            values_to = 'PSI')
head(psi_df_tidy)
```

```{r}
so2_df <- read_excel("SO2.xlsx", sheet = "Sheet1")
head(so2_df)
```

```{r}
install.packages('plyr')
library(plyr)
```

```{r}
so2_df$Region <- revalue(so2_df$Region, c("North" = "N", "South" = "S",
                                          "East" = "E", "West" = "W", "Central" = "C"))
so2_df
```
```{r}
pm10_df <- read_excel("PM10.xlsx")
pm10_df
```
```{r}
install.packages('dplyr')
library(dplyr)
```

```{r}
join_df <- inner_join(so2_df, pm10_df, by = c("Date", "Region"))
join_df
```
```{r}
join_df_full <- inner_join(join_df, psi_df_tidy, by = c("Date", "Region"))
join_df_full
```
```{r}
summary(join_df_full)
```
```{r}
join_df_full <- drop_na(join_df_full)
summary(join_df_full)
```
```{r}
write.csv(join_df_full, file = "output.csv")
```


